import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const hankenRegular = localFont({
  src: "./fonts/HankenGrotesk-Regular.woff",
  variable: "--font-hanken-regular",
  weight: "normal",
});
// const hankenMedium = localFont({
//   src: "./fonts/HankenGrotesk-Medium.ttf",
//   variable: "--font-hanken-medium",
//   weight: "600",
// });
// const hankenLight = localFont({
//   src: "./fonts/HankenGrotesk-Light.ttf",
//   variable: "--font-hanken-light",
//   weight: "200",
// });
// const hankenThin = localFont({
//   src: "./fonts/HankenGrotesk-Thin.ttf",
//   variable: "--font-hanken-thin",
//   weight: "100",
// });
// const hankenBold = localFont({
//   src: "./fonts/HankenGrotesk-Bold.ttf",
//   variable: "--font-hanken-bold",
//   weight: "800",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hankenRegular.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
